Updated Packages
DetroitJS/detroitjs-com pull request #19
Opened 2017-07-29 05:26 UTC by imcodingideas

Per issue #17 I went to reproduce this by running: npm run build. I was not able to reproduce this issue. 

Reading https://github.com/webpack/loader-utils/issues/56 I understood this to be an author problem. You may have had older packages installed. Hopefully this pull request solves it for you.

2017-07-29 13:59 UTC, sixlive requested changes

2017-07-29 13:59 UTC, sixlive commented on package.json
> +    "eslint-plugin-node": "^5.5.1",
```shell
detroitjs-com ▶︎ imcodingideas-build-warning ✓
⚡  npm i
npm ERR! code ETARGET
npm ERR! notarget No matching version found for eslint-plugin-node@^5.5.1
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget
npm ERR! notarget It was specified as a dependency of 'detroitjs.com'
npm ERR! notarget

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/tjmiller/.npm/_logs/2017-07-29T13_56_57_593Z-debug.log
```

With `npm install` I get the following error. With yarn it give me a prompt to select the correct dependency.

2017-07-29 14:21 UTC, imcodingideas commented on package.json
> +    "eslint-plugin-node": "^5.5.1",
@sixlive My bad. I will fix this.

2017-07-29 14:47 UTC, imcodingideas commented
I need to fix these conflicts I guess. 👍

2017-11-06 11:37 UTC, sixlive commented
@imcodingideas I'm going to close this for now. If you want to re-open it with fixes I'd love to merge it!

2017-11-06 11:37 UTC, closed without merging